### PR TITLE
SS-29677: [MOL V3000 writer for Ketcher]: Writes Atom Block and Bond Block

### PR DESCRIPTION
**Pull request by apar03**
- Adds MOL V3000 writer to Ketcher, which constructs the MOL V3000 representation from the underlying [`struct`](https://github.com/schrodinger/ketcher-schrodinger/blob/master/src/script/chem/struct/index.js) data structure.
- This PR addresses writing the Atom block and Bond block, as described in the [CTFile Representation Documentation, Chapter 10: The Extended Connection Table (V3000)](https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf)
- Tested with all sorts of "simplistic sketches". R-Groups, attachment points etc. are also supported

Primary - @mycrobe

### CODE REVIEW

**Comment by apar03** [comment]
Please note that this is a fresh PR, which has been migrated from the earlier private repo (which we're going to delete).
This PR contains the latest code state, so please consider this as the source of truth for further comments and sign-off.

cc @wcjordan @mycrobe

**Comment by mycrobe** [comment]
I'm somewhat uneasy that we're taking on the generation of files in these text formats. Is there really no alternative?

**Comment by apar03** [comment]
> I'm somewhat uneasy that we're taking on the generation of files in these text formats. Is there really no alternative?

We investigated on trying to utilize some of the third party ready-made MOL V3000 writers like Kekule.js, but the challenge we face there is to write an adapter which transforms the Ketcher's Internal Molecular Data Structure into the Kekule.js Structure Object. And for doing that, we need to have complete clarity of both the data structure objects. Given that none of them is documented, it would be an even bigger headache to go along that route. 

On digging a little deeper with the Ketcher's internal molecular data structure, we have realized that it is _somewhat_ verbose (when compared against the chapter 10 of the spec - https://drive.google.com/file/d/0Bx3dsPc7eyZKdXlHTktQTFJUMHc/view)

We feel it should be easier to implement our own writer by making sense out of the Ketcher Data Structure ourselves, rather than having to bear the pain of understanding the Kekule (or any third party Molecule object) too.

**Comment by mycrobe** [comment]
> > I'm somewhat uneasy that we're taking on the generation of files in these text formats. Is there really no alternative?
> 
> We investigated on trying to utilize some of the third party ready-made MOL V3000 writers like Kekule.js, 
<snip>

Thanks for the explanation, @apar03. Makes sense to me.

**Review by mycrobe — APPROVED** [review]
lgtm

**Pull request merged**
